"""Code generation + debugging skill (fully local, stdlib only).

Two real behaviors:

* Template generator — ``function <name> <args>``, ``class <name>``, or
  ``cli <name>`` produce Python source, which is then syntax-checked with
  ``ast.parse`` and reported back.
* Traceback debugger — ``debug <traceback text>`` maps the exception type
  to concrete, heuristic fix suggestions (imports, indentation, missing
  modules, ...).

Generated identifiers are validated; nothing is executed.
"""

from __future__ import annotations

import ast
import re

from skills.base import Skill, SkillContext

_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_SUGGESTIONS: dict[str, str] = {
    "NameError": "the name is used but never defined — check spelling and imports.",
    "UnboundLocalError": (
        "a variable assigned later in the function shadows an outer name — "
        "rename it or declare nonlocal/global."
    ),
    "IndentationError": (
        "inconsistent indentation — check for mixed tabs and spaces and re-indent "
        "with 4 spaces per level."
    ),
    "TabError": "tabs and spaces are mixed in the same file — convert tabs to spaces.",
    "SyntaxError": (
        "invalid syntax near the caret (^) — check brackets, colons, quotes, "
        "and f-string braces."
    ),
    "ModuleNotFoundError": (
        "the module is not installed or not on sys.path — install it "
        "(pip install ...) or fix the import path."
    ),
    "ImportError": "the name cannot be imported from that module — check its exports.",
    "TypeError": "wrong argument type or count — check the call signature.",
    "KeyError": "dict key is missing — use .get() with a default or check available keys.",
    "IndexError": "sequence index out of range — check the length before indexing.",
    "AttributeError": "object has no such attribute — check the object's type and spelling.",
    "ValueError": "right type but bad value — validate inputs before converting.",
    "ZeroDivisionError": "guard the divisor against zero before dividing.",
    "FileNotFoundError": "the path is wrong or the file was never created — check cwd and spelling.",
    "RecursionError": "missing or unreachable base case in a recursive function.",
}


def _validate_name(name: str) -> str:
    if not _NAME_RE.fullmatch(name):
        raise ValueError(f"invalid Python identifier: {name!r}")
    return name


def generate_function(name: str, args: str) -> str:
    """Generate a documented function stub."""
    _validate_name(name)
    arg_list = [part.strip() for part in re.split(r"[,\s]+", args.strip()) if part.strip()]
    for arg in arg_list:
        _validate_name(arg)
    params = ", ".join(arg_list)
    return f'def {name}({params}):\n    """Generated by INZO codegen."""\n    ...\n'


def generate_class(name: str) -> str:
    """Generate a documented class stub."""
    _validate_name(name)
    return (
        f"class {name}:\n"
        '    """Generated by INZO codegen."""\n'
        "\n"
        "    def __init__(self) -> None:\n"
        '        """Initialize the instance."""\n'
        "        ...\n"
    )


def generate_cli(name: str) -> str:
    """Generate a small argparse-based CLI program."""
    _validate_name(name)
    lines = [
        '"""CLI generated by INZO codegen."""',
        "from __future__ import annotations",
        "",
        "import argparse",
        "",
        "",
        "def main() -> None:",
        '    """CLI entry point."""',
        f'    parser = argparse.ArgumentParser(prog="{name}")',
        '    parser.add_argument("--verbose", action="store_true", help="Verbose output.")',
        "    args = parser.parse_args()",
        '    print(f"verbose={args.verbose}")',
        "",
        "",
        'if __name__ == "__main__":',
        "    main()",
        "",
    ]
    return "\n".join(lines)


def check_syntax(source: str) -> tuple[bool, str]:
    """Return (ok, message) after parsing ``source`` with ``ast``."""
    try:
        ast.parse(source)
    except SyntaxError as exc:
        return False, f"syntax error at line {exc.lineno}: {exc.msg}"
    return True, "syntax OK"


def debug_traceback(text: str) -> list[str]:
    """Map exception types found in ``text`` to fix suggestions."""
    found: list[str] = []
    for exc_name, tip in _SUGGESTIONS.items():
        if re.search(rf"\b{re.escape(exc_name)}\b", text):
            found.append(f"{exc_name}: {tip}")
    if not found:
        found.append(
            "no known exception type found — paste the full traceback "
            "including the final exception line."
        )
    return found


class CodegenDebugSkill(Skill):
    """Generates Python templates and explains tracebacks (local)."""

    name = "codegen_debug"
    description = (
        "Generates Python function/class/CLI templates with syntax checking, "
        "and maps pasted tracebacks to heuristic fix suggestions."
    )
    intents = ("code.gen", "code.debug")
    required_capabilities = ("skills.execute",)
    background = True
    local_only = True

    async def handle(self, context: SkillContext) -> str:
        text = context.message.strip()
        lowered = text.lower()
        if lowered.startswith("debug"):
            payload = text[len("debug") :].strip()
            if not payload:
                return "codegen_debug: usage: 'debug <traceback text>'"
            return "traceback analysis:\n" + "\n".join(
                f"- {tip}" for tip in debug_traceback(payload)
            )
        if lowered.startswith("function"):
            rest = text[len("function") :].strip().split(None, 1)
            if not rest:
                return "codegen_debug: usage: 'function <name> [arg1, arg2]'"
            name = rest[0]
            args = rest[1] if len(rest) > 1 else ""
            try:
                source = generate_function(name, args)
            except ValueError as exc:
                return f"codegen error: {exc}"
            return self._report(source)
        if lowered.startswith("class"):
            rest = text[len("class") :].strip().split()
            if not rest:
                return "codegen_debug: usage: 'class <Name>'"
            try:
                source = generate_class(rest[0])
            except ValueError as exc:
                return f"codegen error: {exc}"
            return self._report(source)
        if lowered.startswith("cli"):
            rest = text[len("cli") :].strip().split()
            if not rest:
                return "codegen_debug: usage: 'cli <prog-name>'"
            try:
                source = generate_cli(rest[0])
            except ValueError as exc:
                return f"codegen error: {exc}"
            return self._report(source)
        return (
            "codegen_debug: try 'function <name> [args]', 'class <Name>', "
            "'cli <prog>', or 'debug <traceback text>'."
        )

    @staticmethod
    def _report(source: str) -> str:
        ok, message = check_syntax(source)
        status = "ok" if ok else "FAILED"
        return f"generated source (syntax check {status}: {message}):\n```python\n{source}```"


SKILLS: list[Skill] = [CodegenDebugSkill()]
