"""MQL5 Expert Advisor generator (fully local, stdlib only).

Builds a complete, valid ``.mq5`` Expert Advisor from parameters: an
EMA fast/slow crossover with an RSI filter. The EA uses ``iMA``/``iRSI``
handles created in ``OnInit``, reads closed-bar values with
``CopyBuffer`` in ``OnTick``, and opens positions through ``CTrade`` with
configurable lot size, stop-loss, and take-profit in points.

Pure string templating — no MQL5 toolchain is invoked, so the EA still
needs compiling in MetaEditor before use.
"""

from __future__ import annotations

import shlex
import string
from dataclasses import dataclass
from pathlib import Path

from skills.base import Skill, SkillContext

_TIMEFRAMES = {
    "M1": "PERIOD_M1",
    "M5": "PERIOD_M5",
    "M15": "PERIOD_M15",
    "M30": "PERIOD_M30",
    "H1": "PERIOD_H1",
    "H4": "PERIOD_H4",
    "D1": "PERIOD_D1",
    "W1": "PERIOD_W1",
    "MN1": "PERIOD_MN1",
}


@dataclass(frozen=True)
class EAParams:
    """Validated parameters for the generated Expert Advisor."""

    symbol: str = "EURUSD"
    timeframe: str = "H1"
    fast_ma: int = 12
    slow_ma: int = 26
    rsi_period: int = 14
    rsi_overbought: float = 70.0
    rsi_oversold: float = 30.0
    lot: float = 0.10
    sl_points: int = 200
    tp_points: int = 400


def validate_params(params: EAParams) -> EAParams:
    """Validate EA parameters; raise ValueError on bad input."""
    if not params.symbol or not params.symbol.replace("_", "").isalnum():
        raise ValueError(f"invalid symbol: {params.symbol!r}")
    if params.timeframe not in _TIMEFRAMES:
        raise ValueError(
            f"invalid timeframe: {params.timeframe!r} "
            f"(choose from {', '.join(sorted(_TIMEFRAMES))})"
        )
    if params.fast_ma < 1 or params.slow_ma < 1:
        raise ValueError("MA periods must be positive")
    if params.fast_ma >= params.slow_ma:
        raise ValueError("fast_ma must be smaller than slow_ma")
    if not 2 <= params.rsi_period <= 100:
        raise ValueError("rsi_period must be between 2 and 100")
    if not 0.0 < params.rsi_oversold < params.rsi_overbought < 100.0:
        raise ValueError("need 0 < rsi_oversold < rsi_overbought < 100")
    if params.lot <= 0.0:
        raise ValueError("lot must be positive")
    if params.sl_points < 0 or params.tp_points < 0:
        raise ValueError("sl_points/tp_points cannot be negative")
    return params


_EA_TEMPLATE = string.Template(
    r"""//+------------------------------------------------------------------+
//| $ea_name                                                  |
//| MA-crossover + RSI filter EA generated by INZO mql5_builder      |
//+------------------------------------------------------------------+
#property copyright "INZO"
#property version   "1.00"

#include <Trade\Trade.mqh>

input string        InpSymbol        = "$symbol";
input ENUM_TIMEFRAMES InpTimeframe   = $timeframe;
input int           InpFastMA        = $fast_ma;
input int           InpSlowMA        = $slow_ma;
input int           InpRSIPeriod     = $rsi_period;
input double        InpRSIOverbought = $rsi_overbought;
input double        InpRSIOversold   = $rsi_oversold;
input double        InpLot           = $lot;
input int           InpSLPoints      = $sl_points;
input int           InpTPPoints      = $tp_points;

CTrade trade;

int        g_fast = INVALID_HANDLE;
int        g_slow = INVALID_HANDLE;
int        g_rsi  = INVALID_HANDLE;
const long EXPERT_MAGIC = 20261003;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   g_fast = iMA(InpSymbol, InpTimeframe, InpFastMA, 0, MODE_EMA, PRICE_CLOSE);
   g_slow = iMA(InpSymbol, InpTimeframe, InpSlowMA, 0, MODE_EMA, PRICE_CLOSE);
   g_rsi  = iRSI(InpSymbol, InpTimeframe, InpRSIPeriod, PRICE_CLOSE);
   if(g_fast == INVALID_HANDLE || g_slow == INVALID_HANDLE || g_rsi == INVALID_HANDLE)
   {
      Print("INZO EA: indicator handle creation failed");
      return(INIT_FAILED);
   }
   trade.SetExpertMagicNumber(EXPERT_MAGIC);
   trade.SetDeviationInPoints(10);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(g_fast);
   IndicatorRelease(g_slow);
   IndicatorRelease(g_rsi);
}

//+------------------------------------------------------------------+
//| True when this EA already holds a position on InpSymbol          |
//+------------------------------------------------------------------+
bool HasPosition()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) == InpSymbol &&
         PositionGetInteger(POSITION_MAGIC) == EXPERT_MAGIC)
         return(true);
   }
   return(false);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   double fast[], slow[], rsi[];
   ArraySetAsSeries(fast, true);
   ArraySetAsSeries(slow, true);
   ArraySetAsSeries(rsi, true);
   if(CopyBuffer(g_fast, 0, 0, 3, fast) < 3)
      return;
   if(CopyBuffer(g_slow, 0, 0, 3, slow) < 3)
      return;
   if(CopyBuffer(g_rsi, 0, 0, 3, rsi) < 3)
      return;

   // Signals on closed bars only: index 1 = last closed bar.
   bool bullCross = (fast[1] > slow[1]) && (fast[2] <= slow[2]);
   bool bearCross = (fast[1] < slow[1]) && (fast[2] >= slow[2]);
   bool longSignal  = bullCross && (rsi[1] < InpRSIOverbought);
   bool shortSignal = bearCross && (rsi[1] > InpRSIOversold);

   double point = SymbolInfoDouble(InpSymbol, SYMBOL_POINT);
   if(point <= 0.0)
      return;

   if(longSignal)
   {
      if(HasPosition())
         return;
      double ask = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);
      double sl  = (InpSLPoints > 0) ? ask - InpSLPoints * point : 0.0;
      double tp  = (InpTPPoints > 0) ? ask + InpTPPoints * point : 0.0;
      trade.Buy(InpLot, InpSymbol, ask, sl, tp, "INZO MA+RSI long");
   }
   else if(shortSignal)
   {
      if(HasPosition())
         return;
      double bid = SymbolInfoDouble(InpSymbol, SYMBOL_BID);
      double sl  = (InpSLPoints > 0) ? bid + InpSLPoints * point : 0.0;
      double tp  = (InpTPPoints > 0) ? bid - InpTPPoints * point : 0.0;
      trade.Sell(InpLot, InpSymbol, bid, sl, tp, "INZO MA+RSI short");
   }
}
//+------------------------------------------------------------------+
"""
)


def build_ea(params: EAParams) -> str:
    """Render the complete .mq5 source for validated ``params``."""
    params = validate_params(params)
    ea_name = f"INZO_MA_RSI_{params.symbol}_{params.timeframe}.mq5"
    return _EA_TEMPLATE.substitute(
        ea_name=ea_name,
        symbol=params.symbol,
        timeframe=_TIMEFRAMES[params.timeframe],
        fast_ma=params.fast_ma,
        slow_ma=params.slow_ma,
        rsi_period=params.rsi_period,
        rsi_overbought=params.rsi_overbought,
        rsi_oversold=params.rsi_oversold,
        lot=params.lot,
        sl_points=params.sl_points,
        tp_points=params.tp_points,
    )


def _parse_params(text: str) -> EAParams:
    """Parse ``key=value`` tokens into EAParams (unknown keys ignored)."""
    raw: dict[str, str] = {}
    for token in shlex.split(text):
        if "=" in token:
            key, _, value = token.partition("=")
            raw[key.strip().lower()] = value.strip()

    def _int(key: str, default: int) -> int:
        try:
            return int(raw.get(key, str(default)))
        except ValueError as exc:
            raise ValueError(f"invalid integer for {key}: {raw.get(key)!r}") from exc

    def _float(key: str, default: float) -> float:
        try:
            return float(raw.get(key, str(default)))
        except ValueError as exc:
            raise ValueError(f"invalid number for {key}: {raw.get(key)!r}") from exc

    return EAParams(
        symbol=raw.get("symbol", "EURUSD").upper(),
        timeframe=raw.get("timeframe", "H1").upper(),
        fast_ma=_int("fast_ma", 12),
        slow_ma=_int("slow_ma", 26),
        rsi_period=_int("rsi_period", 14),
        rsi_overbought=_float("rsi_overbought", 70.0),
        rsi_oversold=_float("rsi_oversold", 30.0),
        lot=_float("lot", 0.10),
        sl_points=_int("sl_points", 200),
        tp_points=_int("tp_points", 400),
    )


class Mql5BuilderSkill(Skill):
    """Generates a complete MQL5 MA-crossover + RSI Expert Advisor."""

    name = "mql5_builder"
    description = (
        "Generates a complete, valid MQL5 Expert Advisor (EMA fast/slow "
        "crossover with RSI filter, CTrade entries, SL/TP in points) from "
        "parameters."
    )
    intents = ("mql5.build",)
    required_capabilities = ("skills.execute",)
    background = True
    local_only = True

    async def handle(self, context: SkillContext) -> str:
        try:
            params = validate_params(_parse_params(context.message))
        except ValueError as exc:
            return f"mql5 parameter error: {exc}"
        source = build_ea(params)
        saved = ""
        if context.data_dir is not None:
            try:
                path = Path(context.data_dir) / f"INZO_MA_RSI_{params.symbol}.mq5"
                path.write_text(source, encoding="utf-8")
                saved = f"\nsaved to {path}"
            except OSError as exc:
                saved = f"\n(warning: could not save file: {exc})"
        summary = (
            f"generated MQL5 EA: {params.symbol} {params.timeframe} "
            f"EMA({params.fast_ma}/{params.slow_ma}) RSI({params.rsi_period}) "
            f"lot={params.lot} SL={params.sl_points} TP={params.tp_points}{saved}\n"
            "```mql5\n" + source + "```"
        )
        return summary


SKILLS: list[Skill] = [Mql5BuilderSkill()]
